dependencies:
# build
  - python >=3.9
  - numpy >=2.0
  - ipopt
  - swig
  - meson >=1.3.2
  - compilers
  - pkg-config
  - pip
  - setuptools
  - build
  # pin flang 5, current conda-forge global pin as of 3/13/2025
  # update to flang 19 eventually
  - flang 5*  
# runtime
  - packaging
  - mdolab-baseclasses >=1.3.1
  - scipy >=1.7
  - sqlitedict >=1.6
# testing
  - parameterized
  - testflo
